import Head from 'next/head';
import EnterpriseLayout from '../../components/enterprise/Layout';
import Link from 'next/link';
import { useAppContext } from '../../AppProvider';
import {
  Chart as ChartJS,
  CategoryScale,
  ArcElement,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';
import { Line } from 'react-chartjs-2';
ChartJS.register(
  ArcElement,
  Tooltip,
  Legend,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title
);

const Dashboard = ({ totalReports = '12', totalOrders = '19' }) => {
  const [{ user }] = useAppContext();


  // const options = {
  //   responsive: true,
  //   plugins: {
  //     legend: {
  //       position: 'top',
  //     },
  //     title: {
  //       display: true,
  //       text: 'Gráfica de Registro Semanal',
  //     },
  //   },
  // };
  // const labels = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'];
  // const dataLine = {
  //   labels,
  //   datasets: [
  //     {
  //       label: 'Registro semanal',
  //       data: [9000, 11000, 11200, 10000, 9500],
  //       borderColor: 'rgb(53, 162, 235)',
  //       backgroundColor: 'rgba(53, 162, 235, 0.5)',
  //     },
  //   ],
  // };
  if (user) {
    return (
      <>
        <Head>
          <title>Pa&apos; Come Empresarial | Dashboard</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <EnterpriseLayout>
          <div className="w-full mb-6 text-[#003579] font-[poppins] font-semibold">
            <span>
              ¡Bienvenido,{' '}
              <span className="text-[#4278bf]">{`${user.firstname} ${user.lastname}`}</span>
              !
            </span>
          </div>

          <div className="w-full mb-6 grid lg:grid-cols-3 grid-cols-1 gap-5 gap-y-6 xl:gap-12">
          </div>
          <div className="mb-6">
            <span className="text-blue-900 text-2xl font-semibold">
              Resumen de monitoreo
            </span>
            <div className="h-[3px] w-56 bg-blue-400 self-start rounded-full" />
          </div>
          <div className="mb-6">
            <span className="text-blue-500 italic font-semibold text-lg">
              Ordenes
            </span>
            <div className="flex gap-2">
              <span className="italic font-semibold">
                Un total de {totalOrders} órdenes pendientes.
              </span>
              <Link
                className="underline underline-offset-2 text-blue-400 font-semibold italic"
                href="/enterprise/ordenes"
              >
                Ver más
              </Link>
            </div>
            {/* <div className="flex w-fit h-[400px] rounded-lg shadow-lg">
              <Line className="p-3" options={options} data={dataLine} />
            </div> */}
          </div>
          <div>
            <span className="text-red-500 italic font-semibold text-lg">
              Reportes
            </span>
            <div className="flex gap-2">
              <span className="italic font-semibold">
                Un total de {totalReports} reportes pendientes.
              </span>
              <Link
                className="underline underline-offset-2 text-blue-400 font-semibold italic"
                href="/enterprise/reportes"
              >
                Ver más
              </Link>
            </div>
          </div>
        </EnterpriseLayout>
      </>
    );
  }
};

export default Dashboard;
