import { Anchor, Breadcrumbs, Collapse, Textarea } from '@mantine/core';
import Head from 'next/head';
import Link from 'next/link';
import React, { useState } from 'react';
import { FiArrowLeft, FiCheckCircle, FiHome } from 'react-icons/fi';
import { OrderSummary } from '../../../components/order-summary';
import { useActions } from './useActions';

const ShoppingCart = ({ }) => {

  const { orders, setOrder, onAction } = useActions();
  const items = [
    { title: <FiHome />, href: '/' },
    { title: 'Carrito', href: '/customer/carrito' },
  ].map((item, index) => (
    <Anchor
      className="text-[#003579] font-semibold italic"
      href={item.href}
      key={index}
    >
      {item.title}
    </Anchor>
  ));
  const [ordered, setOrdered] = useState(false);
  const [opened, setOpened] = useState(false);
  const [opened2, setOpened2] = useState(false);
  const [counter, setCounter] = useState(1);
  const [counter2, setCounter2] = useState(1);

  const handleAdd = () => {
    if (counter === 10) {
      return;
    }
    setCounter(counter + 1);
  };
  const handleAdd2 = () => {
    if (counter2 === 10) {
      return;
    }
    setCounter2(counter2 + 1);
  };
  const handleSubstract = () => {
    if (counter === 1) {
      return;
    }
    setCounter(counter - 1);
  };
  const handleSubstract2 = () => {
    if (counter2 === 1) {
      return;
    }
    setCounter2(counter2 - 1);
  };

  return (
    <div className="w-full flex flex-col gap-6">
      <Head>
        <title>Pa&apos; Come | Carrito</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full max-w-[1750px] mx-auto lg:px-24 px-5">
        <Breadcrumbs separator=">">{items}</Breadcrumbs>
      </div>
      <div className="px-5">
        <div className="w-full lg:max-w-[850px] relative mx-auto bg-white rounded-sm shadow flex flex-col px-6 md:px-14 py-8 gap-8">
          <div className=" text-center flex flex-col gap-2 font-[poppins] text-[#1A579A]">
            <span>Aquí te mostramos tus pedidos en carrito</span>
          </div>
          <div className="flex flex-col w-full font-[poppins]">
            <span className="text-2xl text-[#1A579A] font-semibold italic pl-2">
              Carrito
            </span>
            <div className="h-[3px] w-full bg-blue-400 self-start rounded-full"></div>
          </div>

          {orders.map(order => (
            <div key={order.id} className='w-full lg:max-w-[850px] relative mx-auto bg-white rounded-sm shadow flex flex-col px-6 md:px-14 py-8 gap-8'>
              <OrderSummary order={order} setOrder={setOrder} />
              <div className="flex justify-center mt-8 px-10 md:px-24">
                <button
                  onClick={async () => await onAction(order)}
                  className={'bg-green-500 rounded-lg py-2 hover:bg-green-400 text-white uppercase font-semibold w-full'}
                >
                  Ordenar
                </button>
              </div>
            </div>
          ))}
          <div className="text-xs flex justify-center text-center italic text-gray-400">
            Recuerda que 15 minutos despúes de ordenar, no podrás cancelar o
            eliminar
          </div>
        </div>
      </div>
    </div>
  );
};

export default ShoppingCart;
