import { Breadcrumbs } from '@mantine/core';
import Head from 'next/head';
import React from 'react';
import Link from 'next/link';
import { FiHome } from 'react-icons/fi';
import { Menu } from '../../../components/menu'
import { useActions } from './useActions'

const MenuPage = () => {
  const { menu } = useActions()

  const items = [
    { title: <FiHome />, href: '/' },
    { title: 'Plato del día', href: '/customer/lunch' },
  ].map((item, index) => (
    <Link
      className="text-[#003579] font-semibold italic hover:underline underline-offset-2"
      href={item.href}
      key={index}
    >
      {item.title}
    </Link>
  ));
  return (
    <div className="w-full flex flex-col gap-6">
      <Head>
        <title>Pa&apos; Come | Plato del día</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full max-w-[1750px] mx-auto lg:px-24 px-5">
        <Breadcrumbs separator=">">{items}</Breadcrumbs>
      </div>
      <Menu menu={menu} />
    </div>
  );
};

export default MenuPage;
