import { Breadcrumbs } from '@mantine/core';
import Head from 'next/head';
import React from 'react';
import Link from 'next/link';
import { FiHome } from 'react-icons/fi';
import { MainStep } from './accesories/mainStep';
import { ExtrasStep } from './accesories/ExtrasStep';
import { useActions } from './useActions';
import { FormProvider } from '../../../components/react-hook-form/FormProvider';
import { SummaryStep } from './accesories/summaryStep';

const Menu = () => {
  const { currentStep, setCurrentStep, stepOneItems, extraStepItems, methods, onAction, summaryPayload, setSummaryPayload } = useActions()

  const items = [
    { title: <FiHome />, href: '/' },
    { title: 'Plato del día', href: '/customer/lunch' },
  ].map((item, index) => (
    <Link
      className="text-[#003579] font-semibold italic hover:underline underline-offset-2"
      href={item.href}
      key={index}
    >
      {item.title}
    </Link>
  ));
  return (
    <div className="w-full flex flex-col gap-6">
      <Head>
        <title>Pa&apos; Come | Plato del día</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full max-w-[1750px] mx-auto lg:px-24 px-5">
        <Breadcrumbs separator=">">{items}</Breadcrumbs>
      </div>
      <FormProvider methods={methods} onSubmit={onAction}>
        {currentStep === 1 && <MainStep items={stepOneItems} />}
        {currentStep === 2 && <ExtrasStep goBack={() => setCurrentStep(1)} items={extraStepItems} />}
        {currentStep === 3 && <SummaryStep goBack={() => setCurrentStep(2)} summaryPayload={summaryPayload} setSummaryPayload={setSummaryPayload} />}
      </FormProvider>
    </div>
  );
};

export default Menu;
