import Image from "next/image";
import React from "react";
import paComeLogo from "../../../public/assets/logoPaCome.png";
import Link from "next/link";
import Head from "next/head";
import { RHFTextInput } from "../../components/react-hook-form/RHFTextInput";
import { RHFSelectWithQuery } from "../../components/react-hook-form/RHFSelectWithQuery";
import { gql } from "@apollo/client";

import { useActions } from "./useActions";
import { FormProvider } from "../../components/react-hook-form/FormProvider";

const Register = () => {
  const { onSubmit, methods } = useActions();
  return (
    <div className="h-screen flex flex-col bg-white">
      <Head>
        <title>Pa&apos; Come | Registro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[#47ADF5]/30 h-[93%] flex justify-center items-center">
        <div
          id="scrollbar"
          className="w-10/12 lg:w-8/12 overflow-auto flex flex-col md:flex-row h-auto max-h-[96%] py-10 md:py-0 bg-white shadow-lg rounded-lg"
        >
          <div className="md:w-5/12  flex justify-center items-center shrink-0 md:h-auto relative">
            <Image className="shrink-0" width={200} src={paComeLogo} alt="" />
          </div>
          <div className="w-0.5 bg-gray-100 my-10 hidden md:flex rounded-full"></div>
          <div className="md:w-7/12 md:h-full m-5 p-4">
            <FormProvider methods={methods} onSubmit={onSubmit}>
              <div className="self-center text-xl text-[#003579] my-3 md:my-0 font-bold font-[poppins] mb-4">
                Regístrate
              </div>
              <div className="flex flex-col gap-0.5">
                <span className="font-[poppins] text-sm md:text-base text-[#003579] font-semibold">
                  Nombre(s)
                </span>
                <RHFTextInput name={"firstname"} placeholder={"Nombre(s)"} />
              </div>
              <div className="flex flex-col gap-0.5">
                <span className="font-[poppins] text-sm md:text-base text-[#003579] font-semibold">
                  Apellido(s)
                </span>
                <RHFTextInput name={"lastname"} placeholder={"Apellido(s)"} />
              </div>
              <div className="flex flex-col gap-0.5">
                <span className="font-[poppins] text-sm md:text-base text-[#003579] font-semibold">
                  Correo corporativo(si aplica)
                </span>
                <RHFTextInput name={"email"} placeholder={"Correo"} />
              </div>
              <div className="flex flex-col md:flex-row gap-2 w-full">
                <div className="flex flex-col gap-0.5 w-full">
                  <span className="font-[poppins] text-sm md:text-base text-[#003579] font-semibold">
                    Cédula
                  </span>

                  <RHFTextInput name={"cedula"} placeholder={"Cédula"} />
                </div>
                <div className="flex flex-col gap-0.5 w-full">
                  <span className="font-[poppins] text-sm md:text-base text-[#003579] font-semibold">
                    Departamento
                  </span>

                  <RHFSelectWithQuery
                    name={"departmentId"}
                    query={gql`
                        query DepartmentList {
                          items: departmentList {
                            id
                            createdAt
                            updatedAt
                            name
                          }
                        }
                      `}
                  />
                </div>
              </div>
              <div className="flex flex-col gap-0.5">
                <span className="font-[poppins] text-sm md:text-base text-[#003579] font-semibold">
                  Contraseña
                </span>

                <RHFTextInput
                  type="password"
                  name={"password"}
                  placeholder={"Contraseña"}
                />
              </div>
              <div className="flex flex-col gap-0.5">
                <span className="font-[poppins] text-sm md:text-base text-[#003579] font-semibold">
                  Confirmar contraseña
                </span>
                <RHFTextInput
                  type="password"
                  name={"confirmPassword"}
                  placeholder={"Confirmar Contraseña"}
                />
              </div>
              <div className="flex items-center gap-2 mt-2">
                <span className="font-[poppins] text-sm md:text-base text-[#003579] font-semibold">
                  Empresa
                </span>
                <RHFSelectWithQuery
                  label={"Empresa"}
                  name={"companyId"}
                  query={gql`
                      query CompanyList {
                        items: companyList {
                          id
                          createdAt
                          updatedAt
                          name
                          sede
                          location
                        }
                      }
                    `}
                />
              </div>
              {/* <Link href="/login"> */}
              <button
                type="submit"
                className="bg-[#0064CE] hover:bg-blue-500 transition-all mt-3 text-white uppercase font-bold w-full rounded-lg py-2"
              >
                Registrar
              </button>
              {/* </Link> */}
              <div className="flex gap-1 self-center text-[10px] flex-wrap justify-center sm:text-xs font-[poppins]">
                <span className="text-[#1A579A] font-semibold">
                  ¿Ya te has registrado?
                </span>
                <Link
                  className="uppercase italic text-blue-400 underline underline-offset-2 font-semibold"
                  href="/login"
                >
                  Inicia Sesión
                </Link>
              </div>
            </FormProvider>

          </div>
        </div>
      </div>
      <div className="bg-white h-[7%] flex justify-center text-center items-center font-[poppins] text-[#1A579A] font-semibold text-[12px] sm:text-sm">
        © 2022 Todos los derechos reservados
      </div>
    </div>
  );
};

export default Register;
