import Head from 'next/head';
import EnterpriseLayout from '../../../components/enterprise/Layout';

const Empleados = () => {
  return (
    <>
      <Head>
        <title>Pa&apos; Come Empresarial | Empleados</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EnterpriseLayout>Empleados</EnterpriseLayout>
    </>
  );
};
export default Empleados;
