import { Collapse, Modal, Switch, Tabs } from '@mantine/core';
import Head from 'next/head';

import { FiEye, FiPlus } from 'react-icons/fi';
import AdminLayout from '../../../components/admin/Layout';
import { MenuDish } from '../../../components/admin/MenuDish';
import { MenuDishOption } from '../../../components/admin/MenuDishOption';
import { MenuModule } from '../../../components/admin/MenuModule';

const Menu = () => {
  return (
    <>
      <Head>
        <title>Pa&apos; Come Admin | Menú</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayout>
        <div className="w-full flex flex-col gap-8">
          <div className="flex w-full items-center justify-between">
            <div className="w-fit">
              <span className="text-blue-900 text-2xl font-semibold">
                Administrar Menú
              </span>
              <div className="h-[3px] w-40 bg-blue-400 self-start rounded-full"></div>
            </div>
            <div>
              <button className="bg-yellow-400 hover:bg-yellow-300 flex items-center py-1.5 px-4 gap-2 uppercase italic rounded-md">
                <FiEye className="shrink-0" />
                Vista Previa
              </button>
            </div>
          </div>
          <div>
            <Tabs variant="pills" defaultValue="lunch">
              <Tabs.List className="w-fit gap-3 bg-[#1A579A] px-5 py-1.5 rounded-md font-semibold">
                <Tabs.Tab
                  className="text-white hover:text-[#1A579A] font-[poppins]"
                  value="lunch"
                >
                  Plato del día
                </Tabs.Tab>
                <Tabs.Tab
                  className="text-white hover:text-[#1A579A] font-[poppins]"
                  value="cafeteria"
                >
                  Cafetería
                </Tabs.Tab>
                <Tabs.Tab
                  className="text-white hover:text-[#1A579A] font-[poppins]"
                  value="breakfast"
                >
                  Desayunos
                </Tabs.Tab>
                <Tabs.Tab
                  className="text-white hover:text-[#1A579A] font-[poppins]"
                  value="pastry"
                >
                  Repostería
                </Tabs.Tab>
                <Tabs.Tab
                  className="text-white hover:text-[#1A579A] font-[poppins]"
                  value="bakery"
                >
                  Panadería
                </Tabs.Tab>
                <span className="md:text-sm text-xs font-semibold cursor-pointer text-white tracking-wider bg-blue-600 rounded-md px-2.5 min-h-[40px] h-full flex items-center font-[poppins] hover:text-blue-500">
                  <FiPlus size={20} />
                </span>
              </Tabs.List>

              <Tabs.Panel value="lunch" pt="xs">
                <div className="flex flex-col gap-5">
                  <div className="py-4 flex flex-col gap-2">
                    <span className="text-[#1A579A] font-semibold">
                      Precio del plato del día
                    </span>
                    <div className="flex justify-center items-center w-fit border-2 border-[#1A579A] rounded-lg font-[poppins]">
                      <span className="text-gray-400 px-3">$</span>
                      <input
                        className="outline-none max-w-[100px] px-1 font-[poppins] py-2 h-full"
                        type="text"
                        placeholder="150"
                      />
                      <span className="bg-blue-100 rounded-lg py-2 px-3 text-gray-400">
                        DOP
                      </span>
                    </div>
                  </div>
                  <MenuModule title="Plato del día" />
                  <div className="flex flex-col gap-5">
                    <MenuDish title="Arroz" />
                    <MenuDishOption dish="Arroz blanco" />
                    <MenuDishOption dish="Moro de habichuelas" />
                    <MenuDishOption dish="Moro de guandules" />
                  </div>
                  <div className="flex flex-col gap-5">
                    <MenuDish title="Ensalada" />
                    <MenuDishOption dish="Ensalada rusa" />
                    <MenuDishOption dish="Ensalada verde" />
                    <MenuDishOption dish="Ensalada de coditos" />
                  </div>
                </div>
              </Tabs.Panel>

              <Tabs.Panel value="cafeteria" pt="xs">
                Cafetería
              </Tabs.Panel>

              <Tabs.Panel value="breakfast" pt="xs">
                Desayunos
              </Tabs.Panel>

              <Tabs.Panel value="pastry" pt="xs">
                Repostería
              </Tabs.Panel>

              <Tabs.Panel value="bakery" pt="xs">
                Panadería
              </Tabs.Panel>
            </Tabs>
          </div>
        </div>
      </AdminLayout>
    </>
  );
};

export default Menu;
