import { Breadcrumbs, Radio } from '@mantine/core';
import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import { FiHome, FiPlus } from 'react-icons/fi';

const Breakfast = () => {
  const items = [
    { title: <FiHome />, href: '/' },
    { title: 'Desayunos', href: '/customer/breakfast' },
  ].map((item, index) => (
    <Link
      className="text-[#003579] font-semibold italic hover:underline underline-offset-2"
      href={item.href}
      key={index}
    >
      {item.title}
    </Link>
  ));
  return (
    <div className="w-full flex flex-col gap-6">
      <Head>
        <title>Pa&apos; Come | Desayunos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full max-w-[1750px] mx-auto lg:px-24 px-5">
        <Breadcrumbs separator=">">{items}</Breadcrumbs>
      </div>
      <div className="px-5">
        <div className="w-full lg:max-w-[850px] relative mx-auto bg-white rounded-sm shadow flex flex-col px-6 md:px-14 py-8 gap-8">
          <div className=" text-center flex flex-col font-[poppins] text-[#1A579A]">
            <span>Agrega los artículos que necesites a continuación:</span>
          </div>
          <div className="flex flex-col w-full font-[poppins]">
            <div className="w-full flex items-end justify-between">
              <span className="text-2xl text-[#1A579A] font-semibold italic pl-2">
                Desayunos
              </span>
              <span className="text-xs text-gray-400 italic">
                Selecciona lo que desees
              </span>
            </div>
            <div className="h-[3px] w-full bg-orange-400 self-start rounded-full"></div>
          </div>
          <div className="flex flex-col gap-6 italic px-10 lg:px-20 font-[poppins]">
            <div className="flex flex-col gap-2">
              <span className="text-orange-400 font-semibold">Snacks</span>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Mangú <span className="font-semibold">RD$50</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Salami <span className="font-semibold">RD$50</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Huevo Frito <span className="font-semibold">RD$50</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Queso Frito <span className="font-semibold">RD$50</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
            </div>
            <div className="flex flex-col gap-2">
              <span className="text-orange-400 font-semibold">Jugos</span>
              <span className="text-sm font-semibold text-blue-900">
                Sabores
              </span>
              <Radio.Group
                className="pl-5"
                name="juice"
                orientation="vertical"
                spacing="xs"
              >
                <div className="flex text-sm gap-1">
                  <input type="radio" id="chinola" name="juice" />
                  <label for="chinola">Chinola</label>
                </div>
                <div className="flex text-sm gap-1">
                  <input type="radio" id="limon" name="juice" />
                  <label for="limon">Limón</label>
                </div>
                <div className="flex text-sm gap-1">
                  <input type="radio" id="cereza" name="juice" />
                  <label for="cereza">Cereza</label>
                </div>
              </Radio.Group>
            </div>
            <div className="flex flex-col gap-2">
              <span className="text-sm font-semibold text-blue-900">
                Tamaño
              </span>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Pequeño <span className="font-semibold">RD$45</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Mediano <span className="font-semibold">RD$50</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Grande <span className="font-semibold">RD$60</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
            </div>
            <div className="flex flex-col gap-2">
              <span className="text-orange-400 font-semibold">Refresco</span>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Uva 10Oz <span className="font-semibold">RD$40</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Coca Cola 12Oz <span className="font-semibold">RD$50</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Merengue 10Oz <span className="font-semibold">RD$40</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
            </div>
          </div>
          <div className="flex justify-center mt-8 px-10 md:px-24">
            <Link className="w-full" href="/customer/summary">
              <button className="bg-[#0064CE] rounded-lg py-2 hover:bg-blue-600 text-white uppercase font-semibold w-full">
                Ver Resumen de Orden
              </button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Breakfast;
