import { Breadcrumbs, Radio } from '@mantine/core';
import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import { FiArrowLeft, FiHome, FiPlus } from 'react-icons/fi';
import { useAppContext } from '../../AppProvider';
import dayjs from 'dayjs';
import { v4 as generateId } from 'uuid'
import { useRouter } from 'next/router';


const Extras = () => {
  const [{ user }, setGlobalState] = useAppContext();
  const router = useRouter()
  function onSummary() {
    const payload = {
      "details": [
        {
          "name": "Carne Asada",
          "price": 0,
          "quantity": 0,
          "total": 0,
          "isDailyDish": true,
          id: generateId(),
          "comment": ""
        },
        {
          "name": "Arroz Blanco",
          "price": 0,
          "quantity": 0,
          "total": 0,
          "isDailyDish": true,
          id: generateId(),
          "comment": ""
        },
        {
          "name": "Habichuela",
          "price": 0,
          "quantity": 0,
          "total": 0,
          "isDailyDish": true,
          id: generateId(),
          "comment": ""
        },
        {
          "name": "Aguacate",
          "price": 50,
          "quantity": 1,
          "total": 50,
          "isDailyDish": false,
          id: generateId(),
          "comment": ""
        },
        {
          "name": "Bollito de Yuca",
          "price": 50,
          "quantity": 1,
          "total": 50,
          "isDailyDish": false,
          id: generateId(),
          "comment": ""
        },

      ],
      "total": 350,
      "userId": user.id,
      "deliverDate": dayjs().add(1, 'day').toDate(),
      "typeId": 1,
      "dailyDishPrice": 250
    }

    // const payload = {
    //   "details": [
    //     {
    //       "name": "Aguacate",
    //       "price": 50,
    //       "quantity": 1,
    //       "total": 50,
    //       "isDailyDish": false,
    //       "id": generateId(),
    //       "comment": ""
    //     },
    //     {
    //       "name": "Bollito de Yuca",
    //       "price": 50,
    //       "quantity": 1,
    //       "total": 50,
    //       "isDailyDish": false,
    //       "id": generateId(),
    //       "comment": ""
    //     },
    //     {
    //       "name": "Patica de cerdo",
    //       "price": 100,
    //       "quantity": 1,
    //       "total": 100,
    //       "isDailyDish": false,
    //       "id": generateId(),
    //       "comment": ""
    //     },

    //   ],
    //   "total": 200,
    //   "userId": user.id,
    //   "deliverDate": dayjs().add(1, 'day').toDate(),
    //  "typeId": 1,
    //   "dailyDishPrice": 0
    // }

    setGlobalState(state => ({ ...state, toSummary: payload }));

    router.push('/customer/summary');
  }

  const items = [
    { title: <FiHome />, href: '/' },
    { title: 'Plato del día', href: '/customer/lunch' },
    { title: 'Extras', href: '/customer/extras' },
  ].map((item, index) => (
    <Link
      className="text-[#003579] font-semibold italic hover:underline underline-offset-2"
      href={item.href}
      key={index}
    >
      {item.title}
    </Link>
  ));
  return (
    <div className="w-full flex flex-col gap-6">
      <Head>
        <title>Pa&apos; Come | Extras</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full max-w-[1750px] mx-auto lg:px-24 px-5">
        <Breadcrumbs separator=">">{items}</Breadcrumbs>
      </div>
      <div className="px-5">
        <div className="w-full lg:max-w-[850px] relative mx-auto bg-white rounded-sm shadow flex flex-col px-6 md:px-14 py-8 gap-8">
          <div className=" text-center flex flex-col font-[poppins] text-[#1A579A]">
            <div className="md:absolute flex w-full md:justify-start justify-center lg:-ml-8 md:-mt-4 mb-2 md:mb-0">
              <Link
                className=" bg-blue-300 rounded-full p-2"
                href="/customer/lunch"
              >
                <FiArrowLeft className="text-white w-5 h-5" />
              </Link>
            </div>
            <span>Antes de terminar, ¿Deseas agregar un adicional?</span>
            <span className="text-gray-400">
              Recuerda que el total del extra se te sumará al monto del plato
              del día.
            </span>
          </div>
          <div className="flex flex-col w-full font-[poppins]">
            <div className="w-full flex items-end justify-between">
              <span className="text-2xl text-[#1A579A] font-semibold italic pl-2">
                Extras
              </span>
              <span className="text-xs text-gray-400 italic">
                Selecciona lo que desees
              </span>
            </div>
            <div className="h-[3px] w-full bg-orange-400 self-start rounded-full"></div>
          </div>
          <div className="flex flex-col gap-6 italic px-10 lg:px-20 font-[poppins]">
            <div className="flex flex-col gap-2">
              <span className="text-orange-400 font-semibold">
                Acompañantes
              </span>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Aguacate <span className="font-semibold">RD$50</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Fritos maduros <span className="font-semibold">RD$50</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Batatas fritas <span className="font-semibold">RD$50</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Arepitas de maíz <span className="font-semibold">RD$50</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
            </div>
            <div className="flex flex-col gap-2">
              <span className="text-orange-400 font-semibold">Jugos</span>
              <span className="text-sm font-semibold text-blue-900">
                Sabores
              </span>
              <Radio.Group
                className="pl-5"
                name="juice"
                orientation="vertical"
                spacing="xs"
              >
                <div className="flex text-sm gap-1">
                  <input type="radio" id="chinola" name="juice" />
                  <label for="chinola">Chinola</label>
                </div>
                <div className="flex text-sm gap-1">
                  <input type="radio" id="limon" name="juice" />
                  <label for="limon">Limón</label>
                </div>
                <div className="flex text-sm gap-1">
                  <input type="radio" id="cereza" name="juice" />
                  <label for="cereza">Cereza</label>
                </div>
              </Radio.Group>
            </div>
            <div className="flex flex-col gap-2">
              <span className="text-sm font-semibold text-blue-900">
                Tamaño
              </span>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Pequeño <span className="font-semibold">RD$45</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Mediano <span className="font-semibold">RD$50</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Grande <span className="font-semibold">RD$60</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
            </div>
            <div className="flex flex-col gap-2">
              <span className="text-orange-400 font-semibold">Refresco</span>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Uva 10Oz <span className="font-semibold">RD$40</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Coca Cola 12Oz <span className="font-semibold">RD$50</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
              <div className="flex justify-between w-full max-w-[300px]">
                <div>
                  Merengue 10Oz <span className="font-semibold">RD$40</span>
                </div>
                <button className="p-1 bg-orange-400 rounded-full active:scale-95">
                  <FiPlus className="text-white" />
                </button>
              </div>
            </div>
          </div>
          <div className="flex justify-center mt-8 px-10 md:px-24">

            <button onClick={onSummary} className="bg-[#0064CE] rounded-lg py-2 hover:bg-blue-600 text-white uppercase font-semibold w-full">
              Ver Resumen de Orden
            </button>

          </div>
        </div>
      </div>
    </div>
  );
};

export default Extras;
