import { Radio } from '@mantine/core';
import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import riceIcon from '../../../public/icons/riceIcon.svg';
import meatIcon from '../../../public/icons/meatIcon.svg';
import saladIcon from '../../../public/icons/saladIcon.svg';
import Link from 'next/link';

const Lunch = () => {
  return (
    <div className="w-full px-5 sm:px-10">
      <Head>
        <title>Pa&apos; Come | Plato del día</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full lg:max-w-[850px] mx-auto bg-white rounded-sm shadow flex flex-col px-6 md:px-14 py-8 gap-8">
        <div className=" text-center flex font-[poppins] text-[#1A579A]">
          <span>
            Este es nuestro menú del día de hoy, recuerda que el monto total del
            plato del día sin importar la opción que selecciones es de{' '}
            <span className="font-semibold">RD$150.00</span>
          </span>
        </div>

        <div className="flex flex-col gap-6 mb-10">
          <div className="flex flex-col gap-5 font-[poppins]">
            <div className="flex items-end w-full">
              <div className="w-[30px] md:w-auto">
                <Image src={riceIcon} alt="" />
              </div>
              <div className="flex flex-col w-full">
                <div className="w-full flex gap-3 items-end justify-between">
                  <span className="text-2xl text-[#1A579A] font-semibold italic pl-2">
                    Arroz
                  </span>
                  <span className="text-[10px] sm:text-xs text-right text-gray-400 italic">
                    Favor seleccionar una opción
                  </span>
                </div>
                <div className="h-[3px] w-full bg-yellow-400 self-start rounded-full"></div>
              </div>
            </div>
            <div className=" font-semibold italic px-10 lg:px-24">
              <Radio.Group name="rice" orientation="vertical" spacing="xs">
                <div className="flex text-sm gap-1">
                  <input type="radio" id="blanco" name="rice" />
                  <label for="blanco">Arroz blanco</label>
                </div>
                <div className="flex text-sm gap-1">
                  <input type="radio" id="guandules" name="rice" />
                  <label for="guandules">Moro de guandules</label>
                </div>
                <div className="flex text-sm gap-1">
                  <input type="radio" id="habichuela" name="rice" />
                  <label for="habichuela">Moro de habichuelas</label>
                </div>
                <div className="flex text-sm gap-1">
                  <input type="radio" id="none" name="rice" value="" />
                  <label for="none">Ninguno/a</label>
                </div>
              </Radio.Group>
            </div>
          </div>
          <div className="flex flex-col gap-5 font-[poppins]">
            <div className="flex items-end w-full">
              <div className="w-[30px] md:w-auto">
                <Image src={meatIcon} alt="" />
              </div>
              <div className="flex flex-col w-full">
                <div className="w-full flex items-end justify-between">
                  <span className="text-2xl text-[#1A579A] font-semibold italic pl-2">
                    Carnes
                  </span>
                  <span className="text-[10px] sm:text-xs text-right text-gray-400 italic">
                    Favor seleccionar una opción
                  </span>
                </div>
                <div className="h-[3px] w-full bg-red-400 self-start rounded-full"></div>
              </div>
            </div>
            <div className=" font-semibold italic px-10 lg:px-24">
              <Radio.Group name="meat" orientation="vertical" spacing="xs">
                <div className="flex text-sm gap-1">
                  <input type="radio" id="pollo" name="meat" />
                  <label for="pollo">Pollo guisado</label>
                </div>
                <div className="flex text-sm gap-1">
                  <input type="radio" id="cerdo" name="meat" />
                  <label for="cerdo">Cerdo guisado</label>
                </div>
                <div className="flex text-sm gap-1">
                  <input type="radio" id="pechuga" name="meat" />
                  <label for="pechuga">Pechuga a la plancha</label>
                </div>
                <div className="flex text-sm gap-1">
                  <input type="radio" id="noneMeat" name="meat" value="" />
                  <label for="noneMeat">Ninguno/a</label>
                </div>
              </Radio.Group>
            </div>
          </div>
          <div className="flex flex-col gap-5 font-[poppins]">
            <div className="flex items-end w-full">
              <div className="w-[30px] md:w-auto">
                <Image src={saladIcon} alt="" />
              </div>
              <div className="flex flex-col w-full">
                <div className="w-full flex items-end justify-between">
                  <span className="text-2xl text-[#1A579A] font-semibold italic pl-2">
                    Ensalada
                  </span>
                  <span className="text-[10px] sm:text-xs text-right text-gray-400 italic">
                    Favor seleccionar una opción
                  </span>
                </div>
                <div className="h-[3px] w-full bg-green-400 self-start rounded-full"></div>
              </div>
            </div>
            <div className=" font-semibold italic px-10 lg:px-24">
              <Radio.Group name="salad" orientation="vertical" spacing="xs">
                <div className="flex text-sm gap-1">
                  <input type="radio" id="verde" name="salad" />
                  <label for="verde">Ensalada verde</label>
                </div>
                <div className="flex text-sm gap-1">
                  <input type="radio" id="rusa" name="salad" />
                  <label for="rusa">Ensalada rusa</label>
                </div>
                <div className="flex text-sm gap-1">
                  <input type="radio" id="coditos" name="salad" />
                  <label for="coditos">Ensalada de coditos</label>
                </div>
                <div className="flex text-sm gap-1">
                  <input type="radio" id="noneSalad" name="salad" value="" />
                  <label for="noneSalad">Ninguno/a</label>
                </div>
              </Radio.Group>
            </div>
          </div>
        </div>

        <div className="flex justify-center px-10 md:px-24">
          <Link className="w-full" href="/customer/extras">
            <button className="bg-[#0064CE] rounded-lg py-2 hover:bg-blue-600 text-white uppercase font-semibold w-full">
              Siguiente
            </button>
          </Link>
        </div>
      </div>
    </div>
  );
};

export default Lunch;
