import { Anchor, Breadcrumbs, Tabs } from '@mantine/core';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { FiCamera, FiCheckCircle, FiHome } from 'react-icons/fi';
import { RiLock2Line, RiUser2Fill } from 'react-icons/ri';
import profilePicture from '../../../public/assets/profilepicture.png';

const Profile = () => {
  const items = [
    { title: <FiHome />, href: '/' },
    { title: 'Mi Cuenta', href: '/customer/lunch' },
  ].map((item, index) => (
    <Anchor
      className="text-[#003579] font-semibold italic"
      href={item.href}
      key={index}
    >
      {item.title}
    </Anchor>
  ));
  const [saved, setSaved] = useState(false);
  return (
    <div className="w-full flex flex-col gap-6">
      <Head>
        <title>Pa&apos; Come | Mi Cuenta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full max-w-[1750px] mx-auto lg:px-24 px-5">
        <Breadcrumbs separator=">">{items}</Breadcrumbs>
      </div>
      <div className="w-full max-w-[1750px] mx-auto lg:px-24 px-5 grid md:grid-cols-4 gap-5">
        <div className=" grid w-full md:col-span-3 gap-5 order-2 md:order-1">
          <Tabs
            className="flex flex-col"
            styles={() => ({
              tab: {
                '&[data-active]': {
                  background: '#1a579a',
                },
              },
            })}
            variant="pills"
            defaultValue="gallery"
          >
            <Tabs.List className=" mb-3 flex justify-center md:justify-start">
              <Tabs.Tab
                className="font-bold text-sky-600"
                value="gallery"
                icon={<RiUser2Fill />}
              >
                Información de Cuenta
              </Tabs.Tab>

              <Tabs.Tab
                className="font-bold text-sky-600"
                value="messages"
                icon={<RiLock2Line />}
              >
                Cambiar Contraseña
              </Tabs.Tab>
            </Tabs.List>

            <Tabs.Panel
              className="px-10 py-8 space-y-10 rounded-md bg-white"
              value="gallery"
              pt="xs"
            >
              <div className="grid lg:grid-cols-3 col-span-3 gap-x-5 gap-y-5">
                <div className=" lg:col-span-3 w-full mb-1">
                  <span className="text-blue-900 text-2xl font-semibold">
                    General
                  </span>
                  <div className="h-[3px] w-16 bg-blue-400 self-start rounded-full"></div>
                </div>
                <div className=" flex flex-col gap-0.5">
                  <span className="font-[poppins] text-sm xl:text-base text-[#003579] font-semibold">
                    Nombre(s)
                  </span>
                  <input
                    type="text"
                    placeholder="Nombre"
                    className="border-2 border-[#1A579A] px-3 py-2 font-[poppins] placeholder:text-sm rounded-lg w-full outline-none"
                  />
                </div>
                <div className=" flex flex-col gap-0.5">
                  <span className="font-[poppins] text-sm xl:text-base text-[#003579] font-semibold">
                    Apellido(s)
                  </span>
                  <input
                    type="text"
                    placeholder="Apellido"
                    className="border-2 border-[#1A579A] px-3 py-2 font-[poppins] placeholder:text-sm rounded-lg w-full outline-none"
                  />
                </div>
                <div className=" flex flex-col gap-0.5">
                  <span className="font-[poppins] text-sm xl:text-base text-[#003579] font-semibold">
                    Correo electrónico
                  </span>
                  <input
                    type="email"
                    placeholder="Correo"
                    className="border-2 border-[#1A579A] px-3 py-2 font-[poppins] placeholder:text-sm rounded-lg w-full outline-none"
                  />
                </div>
              </div>

              <div className="grid lg:grid-cols-3 col-span-3 gap-x-5 gap-y-5">
                <div className=" lg:col-span-3 w-full mb-1">
                  <span className="text-blue-900 text-2xl font-semibold">
                    Información Personal
                  </span>
                  <div className="h-[3px] w-40 bg-blue-400 self-start rounded-full"></div>
                </div>
                <div className=" flex flex-col gap-0.5">
                  <span className="font-[poppins] text-sm xl:text-base text-[#003579] font-semibold">
                    Cédula
                  </span>
                  <input
                    type="text"
                    placeholder="Cédula"
                    className="border-2 border-[#1A579A] px-3 py-2 font-[poppins] placeholder:text-sm rounded-lg w-full outline-none"
                  />
                </div>
                <div className="flex flex-col gap-0.5">
                  <span className="font-[poppins] text-sm xl:text-base text-[#003579] font-semibold">
                    Teléfono
                  </span>
                  <input
                    type="text"
                    placeholder="Teléfono"
                    className="border-2 border-[#1A579A] px-3 py-2 font-[poppins] placeholder:text-sm rounded-lg w-full outline-none"
                  />
                </div>
                <div className="flex flex-col gap-0.5">
                  <span className="font-[poppins] text-sm xl:text-base text-[#003579] font-semibold">
                    Departamento
                  </span>
                  <input
                    type="text"
                    placeholder="Departamento"
                    className="border-2 border-[#1A579A] px-3 py-2 font-[poppins] placeholder:text-sm rounded-lg w-full outline-none"
                  />
                </div>
              </div>

              <div className="w-full flex flex-col items-center gap-4 justify-center pt-10">
                <button
                  onClick={() => setSaved(!saved)}
                  className={
                    saved
                      ? 'bg-gray-300 rounded-md px-14 py-2 uppercase text-white text-sm font-semibold'
                      : 'bg-sky-800 rounded-md px-14 py-2 uppercase text-white text-sm font-semibold'
                  }
                >
                  Guardar Cambios
                </button>
                {saved ? (
                  <div className="text-sm flex flex-col justify-center items-center gap-2 text-center italic">
                    <div className="flex items-center text-green-500 gap-1 font-semibold">
                      <span className="text-base">
                        Cambios realizados con éxito
                      </span>
                      <FiCheckCircle className="w-4 h-4" />
                    </div>
                  </div>
                ) : (
                  ''
                )}
              </div>
            </Tabs.Panel>

            <Tabs.Panel
              className="px-10 py-8 rounded-md space-y-5 bg-white"
              value="messages"
              pt="xs"
            >
              <div className="grid col-span-3 gap-x-5 gap-y-6">
                <div className=" w-full">
                  <span className="text-blue-900 text-2xl font-semibold">
                    Cambiar Contraseña
                  </span>
                  <div className="h-[3px] w-40 bg-blue-400 self-start rounded-full"></div>
                </div>
                <div className="flex flex-col md:flex-row gap-5 ">
                  <div className="flex flex-col w-full gap-5">
                    <div>
                      <span className="font-[poppins] text-sm xl:text-base text-[#003579] font-semibold">
                        Contraseña Actual
                      </span>
                      <input
                        type="password"
                        placeholder="*******"
                        className="border-2 border-[#1A579A] px-3 py-2 font-[poppins] placeholder:text-sm rounded-lg w-full outline-none"
                      />
                    </div>
                    <div>
                      <p className="text-xs text-gray-500 italic mt-2">
                        Nota: Tu contraseña debe ser mayor o igual a 8
                        caracteres, debe incluir números. Utilice una
                        combinación de mayúsculas y minúsculas. Debe incluir
                        caracteres especiales: - * ? ! @ # $ / () {} = . , ; :
                      </p>
                    </div>
                  </div>
                  <div className="flex flex-col gap-5 w-full">
                    <div className="flex flex-col gap-0.5">
                      <span className="font-[poppins] text-sm xl:text-base text-[#003579] font-semibold">
                        Contraseña Nueva
                      </span>
                      <input
                        type="password"
                        placeholder="*******"
                        className="border-2 border-[#1A579A] px-3 py-2 font-[poppins] placeholder:text-sm rounded-lg w-full outline-none"
                      />
                    </div>
                    <div className="flex flex-col gap-0.5">
                      <span className="font-[poppins] text-sm xl:text-base text-[#003579] font-semibold">
                        Confirmar Contraseña
                      </span>
                      <input
                        type="password"
                        placeholder="*******"
                        className="border-2 border-[#1A579A] px-3 py-2 font-[poppins] placeholder:text-sm rounded-lg w-full outline-none"
                      />
                    </div>
                  </div>
                </div>
              </div>

              <div className="w-full flex justify-center  pt-10">
                <button className="bg-sky-800 rounded-md px-14 py-2 uppercase text-white text-sm">
                  Guardar Cambios
                </button>
              </div>
            </Tabs.Panel>
          </Tabs>
        </div>

        <div className="w-full bg-white md:mt-[45px] rounded-md order-1">
          <div className="flex flex-col items-center gap-4 py-12 h-full">
            <div className=" min-w-[155px] min-h-[155px] flex rounded-full relative">
              <Image
                layout="fill"
                className="rounded-full"
                src={profilePicture}
                alt=""
              />
            </div>
            <div className="flex items-center text-xs gap-1 cursor-pointer text-white bg-sky-700 hover:bg-sky-600 rounded-full px-3 py-1.5 w-fit">
              <FiCamera />
              <span className="uppercase font-semibold">Editar foto</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Profile;
