import Head from 'next/head';
import Link from 'next/link';
import React, { useState } from 'react';
import { FiArrowLeft, FiCheck, FiCheckCircle } from 'react-icons/fi';

const Summary = () => {
  const [ordered, setOrdered] = useState(false);
  console.log(ordered);

  return (
    <div className="w-full px-5 sm:px-10">
      <Head>
        <title>Pa&apos; Come | Resumen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full lg:max-w-[850px] relative mx-auto bg-white rounded-sm shadow flex flex-col px-6 md:px-14 py-8 gap-8">
        <div className=" text-center flex flex-col gap-2 font-[poppins] text-[#1A579A]">
          <div className="md:absolute flex w-full md:justify-start justify-center lg:-ml-8 md:-mt-4 mb-2 md:mb-0">
            <Link
              className=" bg-blue-300 rounded-full p-2"
              href="/customer/extras"
            >
              <FiArrowLeft className="text-white w-5 h-5" />
            </Link>
          </div>
          <span>Aqui te mostramos tu resumen de Orden</span>
        </div>

        <div className="flex flex-col w-full font-[poppins]">
          <span className="text-2xl text-[#1A579A] font-semibold italic pl-2">
            Resumen
          </span>
          <div className="h-[3px] w-full bg-orange-400 self-start rounded-full"></div>
        </div>

        <div className="flex flex-col">
          <div className="flex">
            <div className="flex w-[90%] justify-between items-end border-b pb-2 px-6 xl:px-12">
              <div className="flex flex-col">
                <div className="w-full text-sm text-gray-500">
                  <span>Plato del dia</span>
                </div>
                <div className="flex flex-col text-sm text-gray-500 pl-3 xl:pl-6">
                  <span>x Arroz blanco</span>
                  <span>x Pollo guisado</span>
                  <span>x Ensalada Rusa</span>
                </div>
              </div>
              <div>
                <span className="italic font-semibold">RD$ 150</span>
              </div>
            </div>
            <div className="w-[10%] self-center pl-1">
              <button className="underline italic underline-offset-2 text-blue-400 hover:text-blue-300 text-xs">
                Agregar nota
              </button>
            </div>
          </div>

          <div className="flex flex-col w-[90%] border-b py-2 px-6 xl:px-12">
            <div className="w-full text-sm text-gray-500">
              <span>Extras</span>
            </div>
          </div>
          <div className="flex flex-col w-[90%] bg-blue-100 border-b py-1 italic font-semibold text-blue-900 px-6 xl:px-12">
            <div className="flex justify-between">
              <div className="flex">
                <span className="max-w-[90px] min-w-[90px]">Cant.</span>
                <span>Producto</span>
              </div>
              <div>Total</div>
            </div>
          </div>
          <div className="w-full flex">
            <div className="flex flex-col w-[90%] border-b py-2 px-6 xl:px-12">
              <div className="flex justify-between">
                <div className="flex gap-10 ">
                  <input
                    className="w-12 border-2 border-blue-300 outline-none px-1.5 py-1 rounded-lg text-xs"
                    type="number"
                    name=""
                    id=""
                    defaultValue={1}
                    min={1}
                    max={5}
                  />
                  <span className="truncate pr-2">x Aguacate</span>
                </div>
                <div className="italic text-blue-900 font-semibold">RD$45</div>
              </div>
            </div>
            <div className="w-[10%] self-center pl-1">
              <button className="underline italic underline-offset-2 text-blue-400 hover:text-blue-300 text-xs">
                Agregar nota
              </button>
            </div>
          </div>
          <div className="w-full flex">
            <div className="flex flex-col w-[90%] border-b py-2 px-6 xl:px-12">
              <div className="flex justify-between">
                <div className="flex gap-10  truncate">
                  <input
                    className="w-12 border-2 border-blue-300 outline-none px-1.5 py-1 rounded-lg text-xs"
                    type="number"
                    name=""
                    id=""
                    defaultValue={1}
                    min={1}
                    max={5}
                  />
                  <span className="truncate pr-2">x Jugo Chinola Pequeño</span>
                </div>
                <div className="italic text-blue-900 font-semibold">RD$45</div>
              </div>
            </div>
            <div className="w-[10%] self-center pl-1">
              <button className="underline italic underline-offset-2 text-blue-400 hover:text-blue-300 text-xs">
                Agregar nota
              </button>
            </div>
          </div>
        </div>

        <div className="italic text-xl font-semibold">
          Total de Orden: RD$240
        </div>

        <div className="flex justify-center mt-8 px-10 md:px-24">
          <button
            onClick={() => setOrdered(!ordered)}
            className={
              ordered
                ? 'bg-gray-300 rounded-lg py-2 hover:bg-gray-200 text-white uppercase font-semibold w-full'
                : 'bg-green-500 rounded-lg py-2 hover:bg-green-400 text-white uppercase font-semibold w-full'
            }
          >
            Ordenar
          </button>
        </div>

        {ordered ? (
          <div className="text-sm flex flex-col justify-center items-center gap-2 text-center italic">
            <div className="flex items-center text-green-500 gap-1 font-semibold">
              <span className="text-base">Orden realizada con éxito</span>
              <FiCheckCircle className="w-4 h-4" />
            </div>
            <Link
              className="underline underline-offset-2 text-blue-400"
              href="/customer/ordenes"
            >
              Ordenes
            </Link>
          </div>
        ) : (
          <div className="text-xs flex justify-center text-center italic text-gray-400">
            Recuerda que 15 minutos despúes de ordenar, no podrás cancelar o
            eliminar
          </div>
        )}
      </div>
    </div>
  );
};

export default Summary;
