import Head from 'next/head';
import EnterpriseLayout from '../../../components/enterprise/Layout';

const Administradores = () => {
  return (
    <>
      <Head>
        <title>Pa&apos; Come Empresarial | Administradores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EnterpriseLayout>Administradores</EnterpriseLayout>
    </>
  );
};
export default Administradores;
