import Head from "next/head";
import { MainGrid } from "../components/customer/home/MainGrid";
import { TodayOrders } from "../components/customer/home/TodayOrders";

export default function Home({ user = 'Juan Pérez' }) {
  return (
    <div className="h-full">
      <Head>
        <title>Pa&apos; Come | Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full max-w-[1750px] mx-auto lg:px-24 px-5 mb-6 text-[#003579] font-[poppins] font-semibold">
        <span>
          ¡Bienvenido, <span className="text-[#4278bf]">{user}</span>!
        </span>
      </div>
      <MainGrid />
      <TodayOrders />
    </div>
  );
}
