import Head from 'next/head';
import { MainGrid } from '../components/customer/home/MainGrid';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pa&apos; Come | Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainGrid />
    </div>
  );
}
