import { Breadcrumbs } from '@mantine/core';
import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import { FiHome } from 'react-icons/fi';
// import { OrderCard } from '../../../components/customer/home/OrderCard';
import { TodayOrders } from '../../../components/customer/home/TodayOrders';
import { OrderCard } from '../../../components/order-card';
import { v4 as generateId } from 'uuid'
import { useActions } from './useActions';



const Ordenes = () => {
  const { ordersComfirmedOrDelivered, ordersOrdenated } = useActions();
  const items = [
    { title: <FiHome />, href: '/' },
    { title: 'Ordenes', href: '/customer/ordenes' },
  ].map((item, index) => (
    <Link
      className="text-[#003579] font-semibold italic hover:underline underline-offset-2"
      href={item.href}
      key={index}
    >
      {item.title}
    </Link>
  ));

  return (
    <div className="w-full flex flex-col gap-6">
      <Head>
        <title>Pa&apos; Come | Ordenes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full max-w-[1750px] mx-auto lg:px-24 px-5">
        <Breadcrumbs separator=">">{items}</Breadcrumbs>
      </div>
      <div>
        <div className="w-full flex flex-col gap-5 max-w-[1750px] bg-white mx-auto px-10 lg:px-24 py-8">
          <div className=" w-fit">
            <span className="text-blue-900 text-2xl font-semibold">
              Pendientes por confirmar
            </span>
            <div className="h-[3px] w-30 bg-blue-400 self-start rounded-full"></div>
          </div>
          <div className="grid lg:grid-cols-3 gap-5 lg:gap-10">
            {ordersOrdenated.map(order => (
              <OrderCard key={order.id} order={order} />
            ))}

          </div>
        </div>
        <div className="w-full">
          <div className="w-full flex flex-col gap-5 max-w-[1750px] bg-white mx-auto px-10 lg:px-24 py-8">
            <div className=" w-fit">
              <span className="text-blue-900 text-2xl font-semibold">
                Tus ordenes de hoy
              </span>
              <div className="h-[3px] w-50 bg-blue-400 self-start rounded-full"></div>
            </div>
            <div className="grid lg:grid-cols-3 gap-5 lg:gap-10">
              {ordersComfirmedOrDelivered.map(order => (
                <OrderCard key={order.id} order={order} />
              ))}

            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Ordenes;
