import { Group, Modal, Tabs, Text } from '@mantine/core';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { FiCamera, FiCheckCircle } from 'react-icons/fi';
import { RiLock2Line, RiUser2Fill } from 'react-icons/ri';
import AdminLayout from '../../components/admin/Layout';
import profilePicture from '../../../public/assets/profilepicture.png';
import imageNonFound from '../../../public/assets/non-image.png';
import { Dropzone } from '@mantine/dropzone';
import { MdInsertPhoto } from 'react-icons/md';
import { AiOutlineCloudUpload } from 'react-icons/ai';
import { GiCancel } from 'react-icons/gi';

const Account = () => {
  const [saved, setSaved] = useState(false);
  const [open, setOpen] = useState(false);
  return (
    <>
      <Head>
        <title>Pa&apos; Come Admin | Cuenta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayout>
        <div className="w-full grid md:grid-cols-4 gap-5">
          <div className=" grid w-full md:col-span-3 gap-5 order-2 md:order-1">
            <Tabs
              className="flex flex-col"
              styles={() => ({
                tab: {
                  '&[data-active]': {
                    background: '#1a579a',
                  },
                },
              })}
              variant="pills"
              defaultValue="gallery"
            >
              <Tabs.List className=" mb-3 flex justify-center md:justify-start">
                <Tabs.Tab
                  className="font-bold text-sky-600"
                  value="gallery"
                  icon={<RiUser2Fill />}
                >
                  Información de Cuenta
                </Tabs.Tab>

                <Tabs.Tab
                  className="font-bold text-sky-600"
                  value="messages"
                  icon={<RiLock2Line />}
                >
                  Cambiar Contraseña
                </Tabs.Tab>
              </Tabs.List>

              <Tabs.Panel className=" space-y-6" value="gallery" pt="xs">
                <div className="grid lg:grid-cols-3 col-span-3 gap-x-5 gap-y-2">
                  <div className=" lg:col-span-3 w-full mb-1">
                    <span className="text-blue-900 text-2xl font-semibold">
                      General
                    </span>
                    <div className="h-[3px] w-16 bg-blue-400 self-start rounded-full"></div>
                  </div>
                  <div className=" flex flex-col gap-0.5">
                    <span className="font-[poppins] text-sm xl:text-base text-[#003579] font-semibold">
                      Nombre(s)
                    </span>
                    <input
                      type="text"
                      placeholder="Nombre"
                      className="border-2 border-[#1A579A] px-3 py-2 font-[poppins] placeholder:text-sm rounded-lg w-full outline-none"
                    />
                  </div>
                  <div className=" flex flex-col gap-0.5">
                    <span className="font-[poppins] text-sm xl:text-base text-[#003579] font-semibold">
                      Apellido(s)
                    </span>
                    <input
                      type="text"
                      placeholder="Apellido"
                      className="border-2 border-[#1A579A] px-3 py-2 font-[poppins] placeholder:text-sm rounded-lg w-full outline-none"
                    />
                  </div>
                  <div className=" flex flex-col gap-0.5">
                    <span className="font-[poppins] text-sm xl:text-base text-[#003579] font-semibold">
                      Correo electrónico
                    </span>
                    <input
                      type="email"
                      placeholder="Correo"
                      className="border-2 border-[#1A579A] px-3 py-2 font-[poppins] placeholder:text-sm rounded-lg w-full outline-none"
                    />
                  </div>
                </div>

                <div className="grid lg:grid-cols-3 col-span-3 gap-x-5 gap-y-2">
                  <div className=" lg:col-span-3 w-full mb-1">
                    <span className="text-blue-900 text-2xl font-semibold">
                      Información Personal
                    </span>
                    <div className="h-[3px] w-40 bg-blue-400 self-start rounded-full"></div>
                  </div>
                  <div className=" flex flex-col gap-0.5">
                    <span className="font-[poppins] text-sm xl:text-base text-[#003579] font-semibold">
                      Cédula
                    </span>
                    <input
                      type="text"
                      placeholder="Cédula"
                      className="border-2 border-[#1A579A] px-3 py-2 font-[poppins] placeholder:text-sm rounded-lg w-full outline-none"
                    />
                  </div>
                  <div className="flex flex-col gap-0.5">
                    <span className="font-[poppins] text-sm xl:text-base text-[#003579] font-semibold">
                      Teléfono
                    </span>
                    <input
                      type="text"
                      placeholder="Teléfono"
                      className="border-2 border-[#1A579A] px-3 py-2 font-[poppins] placeholder:text-sm rounded-lg w-full outline-none"
                    />
                  </div>
                  <div className="flex flex-col gap-0.5">
                    <span className="font-[poppins] text-sm xl:text-base text-[#003579] font-semibold">
                      Departamento
                    </span>
                    <input
                      type="text"
                      placeholder="Departamento"
                      className="border-2 border-[#1A579A] px-3 py-2 font-[poppins] placeholder:text-sm rounded-lg w-full outline-none"
                    />
                  </div>
                </div>
              </Tabs.Panel>

              <Tabs.Panel className="space-y-6" value="messages" pt="xs">
                <div className="grid col-span-3 gap-x-5 gap-y-3">
                  <div className=" w-full">
                    <span className="text-blue-900 text-2xl font-semibold">
                      Cambiar Contraseña
                    </span>
                    <div className="h-[3px] w-40 bg-blue-400 self-start rounded-full"></div>
                  </div>
                  <div className="flex flex-col md:flex-row gap-5 ">
                    <div className="flex flex-col w-full gap-5">
                      <div>
                        <span className="font-[poppins] text-sm xl:text-base text-[#003579] font-semibold">
                          Contraseña Actual
                        </span>
                        <input
                          type="password"
                          placeholder="*******"
                          className="border-2 border-[#1A579A] px-3 py-2 font-[poppins] placeholder:text-sm rounded-lg w-full outline-none"
                        />
                      </div>
                      <div>
                        <p className="text-xs text-gray-500 italic mt-2">
                          Nota: Tu contraseña debe ser mayor o igual a 8
                          caracteres, debe incluir números. Utilice una
                          combinación de mayúsculas y minúsculas. Debe incluir
                          caracteres especiales: - * ? ! @ # $ / () {} = . , ; :
                        </p>
                      </div>
                    </div>
                    <div className="flex flex-col gap-5 w-full">
                      <div className="flex flex-col gap-0.5">
                        <span className="font-[poppins] text-sm xl:text-base text-[#003579] font-semibold">
                          Contraseña Nueva
                        </span>
                        <input
                          type="password"
                          placeholder="*******"
                          className="border-2 border-[#1A579A] px-3 py-2 font-[poppins] placeholder:text-sm rounded-lg w-full outline-none"
                        />
                      </div>
                      <div className="flex flex-col gap-0.5">
                        <span className="font-[poppins] text-sm xl:text-base text-[#003579] font-semibold">
                          Confirmar Contraseña
                        </span>
                        <input
                          type="password"
                          placeholder="*******"
                          className="border-2 border-[#1A579A] px-3 py-2 font-[poppins] placeholder:text-sm rounded-lg w-full outline-none"
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </Tabs.Panel>
            </Tabs>
          </div>

          <div className="w-full bg-blue-50 md:mt-[45px] flex justify-center items-center rounded-md order-1">
            <div className="flex flex-col justify-center items-center gap-4 py-12 h-full">
              <div className=" min-w-[155px] min-h-[155px] flex rounded-full relative">
                <Image
                  layout="fill"
                  className="rounded-full"
                  src={profilePicture}
                  alt=""
                />
              </div>

              <Modal
                centered
                title={'Carga una foto de perfil'}
                opened={open}
                onClose={() => setOpen(false)}
                size={'60%'}
              >
                <div className="flex justify-center gap-5">
                  <Dropzone>
                    <Group
                      position="center"
                      spacing="xl"
                      style={{ minHeight: 220, pointerEvents: 'none' }}
                    >
                      <Dropzone.Accept>
                        <AiOutlineCloudUpload
                          size={50}
                          stroke={1.5}
                          color={'dark'}
                        />
                      </Dropzone.Accept>
                      <Dropzone.Reject>
                        <GiCancel
                          size={50}
                          // stroke={1.5}
                          color={'red'}
                        />
                      </Dropzone.Reject>
                      <Dropzone.Idle>
                        <MdInsertPhoto size={50} stroke={1.5} />
                      </Dropzone.Idle>

                      <div>
                        <Text size="xl" inline>
                          Arrastra tu imagen acá o haz click aquí para cargarla
                        </Text>
                        <Text size="sm" color="dimmed" inline mt={7}>
                          Las imágenes no pueden exceder de los 5MB.
                        </Text>
                      </div>
                    </Group>
                  </Dropzone>
                  <Image
                    width={250}
                    height={0}
                    src={imageNonFound}
                    alt={'load-image'}
                  />
                </div>
              </Modal>

              <div
                onClick={() => setOpen(true)}
                className="flex items-center text-xs gap-1 cursor-pointer text-white bg-sky-700 hover:bg-sky-600 rounded-full px-3 py-1.5 w-fit"
              >
                <FiCamera />
                <span className="uppercase font-semibold">Editar foto</span>
              </div>
            </div>
          </div>

          <div className="w-full flex flex-col items-center gap-1 justify-center order-3 col-span-4 pt-8">
            <button
              onClick={() => setSaved(!saved)}
              className={
                saved
                  ? 'bg-gray-300 rounded-md px-14 py-2 uppercase text-white text-sm font-semibold'
                  : 'bg-sky-800 rounded-md px-14 py-2 uppercase text-white text-sm font-semibold'
              }
            >
              Guardar Cambios
            </button>
            {saved ? (
              <div className="text-sm flex flex-col justify-center items-center gap-2 text-center italic">
                <div className="flex items-center text-green-500 gap-1 font-semibold">
                  <span className="text-base">
                    Cambios realizados con éxito
                  </span>
                  <FiCheckCircle className="w-4 h-4" />
                </div>
              </div>
            ) : (
              ''
            )}
          </div>
        </div>
      </AdminLayout>
    </>
  );
};

export default Account;
