import Head from 'next/head';
import AdminLayout from '../../components/admin/Layout';

const Account = () => {
  return (
    <>
      <Head>
        <title>Pa&apos; Come Admin | Cuenta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayout>
        <div>Cuenta</div>
      </AdminLayout>
    </>
  );
};

export default Account;
