import Head from 'next/head';
import { GiSandsOfTime } from 'react-icons/gi';
import AdminLayout from '../../components/admin/Layout';
import Link from 'next/link';
import bell from '../../../public/assets/campana.png';
import Image from 'next/image';
import { useAppContext } from '../../AppProvider';

const Dashboard = ({ totalReports = '12' }) => {
  const [{ user }] = useAppContext();
  if (user) {
    return (
      <>
        <Head>
          <title>Pa&apos; Come Admin | Dashboard</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <AdminLayout>
          <div className="w-full mb-6 text-[#003579] font-[poppins] font-semibold">
            <span>
              ¡Bienvenido,{' '}
              <span className="text-[#4278bf]">{`${user.firstname} ${user.lastname}`}</span>
              !
            </span>
          </div>
          <div className="w-full mb-6 grid lg:grid-cols-3 grid-cols-1 gap-5 gap-y-6 xl:gap-12">
            <div className="lg:w-full w-full max-w-[400px] mx-auto rounded-lg shadow-md flex flex-col justify-around font-[poppins] items-center px-3 lg:px-10 min-h-[350px] py-6 gap-6 text-center bg-white">
              <span className="text-blue-900 italic text-xl md:text-2xl px-3 ">
                Tiempo disponible
              </span>
              <GiSandsOfTime className="text-blue-500" size={130} />
              <span className="text-blue-900 italic font-semibold text-4xl">
                00:00:00
              </span>
            </div>

            <div className="lg:w-full relative w-full max-w-[400px] mx-auto rounded-lg shadow-md flex flex-col justify-around font-[poppins] items-center px-3 xl:px-10 min-h-[350px] py-6 gap-6 text-center bg-white">
              <div className="w-fit absolute right-0 top-0 p-4">
                <Image src={bell} alt="Bell" />
              </div>
              <span className="text-blue-900 italic text-xl md:text-2xl px-3 xl:px-5">
                Pedidos
              </span>
              <div className="border-4 text-7xl italic border-blue-500 text-blue-500 p-6 rounded-full">
                15
              </div>
              <Link
                className="text-lg underline underline-offset-2 italic text-blue-500"
                href="/admin/pedidos"
              >
                Ver todos
              </Link>
            </div>

            <div className="lg:w-full w-full max-w-[400px] mx-auto rounded-lg shadow-md flex flex-col justify-around font-[poppins] items-center px-3 xl:px-10 min-h-[350px] py-6 gap-6 text-center bg-white">
              <span className="text-blue-900 italic text-xl md:text-2xl px-3 xl:px-5">
                Solicitudes
              </span>
              <div className="bg-blue-500 text-7xl italic text-white p-7 rounded-full">
                18
              </div>
              <Link
                className="text-lg underline underline-offset-2 italic text-blue-500"
                href="/admin/empleados/requests"
              >
                Ver todas
              </Link>
            </div>
          </div>
          <div className="mb-6">
            <span className="text-blue-900 text-2xl font-semibold">
              Resumen de monitoreo
            </span>
            <div className="h-[3px] w-56 bg-blue-400 self-start rounded-full" />
          </div>
          <div>
            <span className="text-red-500 italic font-semibold text-lg">
              Reportes
            </span>
            <div className="flex gap-2">
              <span className="italic font-semibold">
                Un total de {totalReports} reportes pendientes.
              </span>
              <Link
                className="underline underline-offset-2 text-blue-400 font-semibold italic"
                href="/admin/reportes"
              >
                Ver más
              </Link>
            </div>
          </div>
        </AdminLayout>
      </>
    );
  }
};

export default Dashboard;
