import Head from 'next/head';
import AdminLayout from '../../components/admin/Layout';

const Menu = () => {
  return (
    <>
      <Head>
        <title>Pa&apos; Come Admin | Menú</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AdminLayout>
        <div>Menu</div>
      </AdminLayout>
    </>
  );
};

export default Menu;
