import { createStyles, Group, Pagination, Table } from '@mantine/core';
import dayjs from 'dayjs';
import Head from 'next/head';
import { BiSave } from 'react-icons/bi';

import AdminLayout from '../../../components/admin/Layout';
import { FormProvider } from '../../../components/react-hook-form/FormProvider';
import { RHFTextInput } from '../../../components/react-hook-form/RHFTextInput';

import { useActions } from './useActions';


const Reportes = () => {
   const { generalParameters, methods, onSave } = useActions();


   return (
      <>
         <Head>
            <title>Pa&apos; Come Admin | Reportes</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <AdminLayout>
            <div className="w-fit">
               <span className="text-blue-900 text-2xl font-semibold">
                  Parámetros Generales
               </span>
               <div className="h-[3px] w-16 bg-blue-400 self-start rounded-full" />
            </div>
            <div className="w-full flex flex-col gap-8 mt-10">
               <div className="flex flex-col gap-6">
                  <div id="scrollbar" className="w-auto overflow-auto">
                     <FormProvider methods={methods} onSubmit={onSave}>
                        <Table highlightOnHover verticalSpacing="sm">
                           <thead className="bg-[#47ADF5]/30 italic font-[poppins] ">
                              <tr>
                                 <th>ID</th>
                                 <th>Nombre</th>
                                 <th>Descripción</th>
                                 <th>Valor</th>
                                 <th>Fecha de Creación</th>
                              </tr>
                           </thead>
                           <tbody className="font-[poppins]">{generalParameters.map((g, index) => (
                              <tr key={g.id}>
                                 <td>{g.id}</td>
                                 <td>{g.name}</td>
                                 <td>{g.description}</td>
                                 <td><RHFTextInput name={`items[${index}].value`} /></td>
                                 <td>{dayjs(g.createdAt).format('DD/MM/YYYY')}</td>
                              </tr>
                           ))}</tbody>

                        </Table>
                        <Group className='mt-5 flex justify-end'>
                           <button
                              type='submit'
                              className=" text-white bg-blue-400 hover:bg-blue-300 flex items-center py-1.5 px-4 gap-2 uppercase italic rounded-md"
                           >
                              <BiSave />
                              Guardar
                           </button>
                        </Group>
                     </FormProvider>
                  </div>
               </div>
            </div>
         </AdminLayout>
      </>
   );
};

export default Reportes;
